### ISSUE TITLE
Approach to get GroupInfo of the Private Group

### ISSUE THREAD

**Issue by sumitzarkar** [Esri/application-boilerplate-js#43]
@driskull ,

When using boilerplate for developing a gallery app, we see that it does not get the group info and does not invoke identity manager too in case of private groups. 

It is required in our case to show the identity manager on app load, hence we are invoking it after boilerplate runs. As the group is private, and boilerplate did not provide the detailed group info, we want to now get the group info again after user signs in. 

We are able to get the groupInfo by using method _queryGroupInfo(). However, we think this is a private method of the boilerplate. 

Please suggest if this approach is OK.

**Comment by driskull** [comment]
@sumitzarkar correct. The boilerplate doesn't support private groups currently. We're looking to change that though.

We can make _queryGroupInfo a public method as well.

I will rename it so you can call it if you'd like.

**Comment by sumitzarkar** [comment]
Sounds good, thank you !

**Comment by driskull** [comment]
@kellyhutchins do you think we should have something to handle private groups? Should this be done API side to work how getItem does where it will prompt you if necessary?

Also, I've had a report that getting items from private group is showing some public items instead of responding with auth error.

**Comment by kellyhutchins** [comment]
@driskull we'd have to test to see how it works - I'm fine with the boilerplate handling private groups if we can get it to work. I remember that in the past we had issues with not having a way to know that there was private content because we were not getting the auth error. If that's the case then apps who want to show private content may have to use the sign-in link approach.

**Comment by driskull** [comment]
@kellyhutchins Yes, we should push for a portal function to check and see if a group requires auth and prompt if so. Ideally, this could happen with getItems() or getInfo(). We had discussed this before. issue 1070 in devtopia.

**Comment by driskull** [comment]
this should be better in 4x. closing
