### ISSUE TITLE
Locally hosted template incorrectly overrides helperServices in default.js

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/application-boilerplate-js#54]
When this template is hosted locally the helperServices settings in default.js are incorrectly overridden in template.js _mixinAll function.

**Comment by driskull** [comment]
@jgrayson-apl do you see any issue with mixing in the application config or url param values into the config or is it just the organization settings with helper services that you see an issue with?

We could not mix those in but then the developer would have to handle mixing it in or writing something like this:

```javascript
var url =
this.config.helperServices.geometry.url ||
this.orgConfig.helperServices.geometry.url;

esriConfig.defaults.geometryService = new GeometryService(url);
```

**Comment by kellyhutchins** [comment]
@driskull @jgrayson-apl   that could be a lot of code that the dev would have to write if they use a bunch of helper services and then we'd have to maintain defaults somewhere and keep them up to date. This is originally why we had the common config. 
Since we can already skip mixing in the org settings by setting the queryForOrg param to false I'd like to avoid this.

**Comment by driskull** [comment]
ok. Lets just leave it open and revisit it later.

**Comment by driskull** [comment]
closing.
