### ISSUE TITLE
Abstract main.js functions into class

### ISSUE THREAD

**Issue by driskull** [Esri/application-boilerplate-js#92]
Abstract main.js functions into class app.js?

**Comment by alaframboise** [comment]
I don't think we need to move functions or passing boilerplate params from main.js to another app.js. Let's just call the main.js  - app.js and have users create their own app class for their template. If they want to reuse code and error handling they can, otherwise they can just do their own thing in their own myApp.js file. This will also avoid future merge conflicts. See #95.
